{
  "openapi": "3.0.0",
  "info": {
    "title": "SYRIA BAZAR API'S",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://bazar-syria.vercel.app/auth"
    },
    {
      "url": "https://bazar-syria.vercel.app/user"
    },
    {
      "url": "https://bazar-syria.vercel.app/category"
    },
    {
      "url": "https://bazar-syria.vercel.app/subcategory"
    },
    {
      "url": "https://bazar-syria.vercel.app/products"
    }
  ],
  "components": {
    "securitySchemes": {
      "noauthAuth": {
        "type": "http",
        "scheme": "noauth"
      },
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "tags": [
    {
      "name": "Authentication"
    },
    {
      "name": "User"
    },
    {
      "name": "Category"
    },
    {
      "name": "SubCategory"
    },
    {
      "name": "Products"
    }
  ],
  "paths": {
    "/google": {
      "get": {
        "tags": ["Authentication"],
        "summary": "Google Authentication",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/login": {
      "post": {
        "tags": ["Authentication"],
        "summary": "Login",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "mahmoud@syria.com",
                  "password": "mahmoud@123"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "312"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"138-bQdsVQABPDKfL/lwzHpUER2SsS8\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sun, 19 Jan 2025 18:34:55 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTIxNTk5OSwiZW1haWwiOiJvbWFyQHN5cmlhLmNvbSIsIm5hbWUiOiJNYWhtb3VkIEFobWVkIiwiYXZhdGFyIjoiU2F0IEphbiAxOCAyMDI1cGVyc29uXzEuanBlZyIsImZvbGxvd2VycyI6MCwiZm9sbG93aW5nIjowLCJpYXQiOjE3MzczMTE2OTUsImV4cCI6MTc0NTA4NzY5NX0.t_S1Lq_q-eNpdwsHg0_f_qDqnnk_RfIF-AkXsioA600"
                }
              }
            }
          }
        }
      }
    },
    "/": {
      "post": {
        "tags": ["Products"],
        "summary": "Add New Product",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "categoryId": "679397800a12449cffe50418",
                  "subCategoryId": "6793c149f406ee7da2520cda",
                  "name": "BMW X6",
                  "description": "BMW X6 New Generation"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "303"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"12f-R6ImjxumiNf9bswlkqBVnsJdg1I\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 24 Jan 2025 18:06:36 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Product created successfully",
                  "product": {
                    "categoryId": "679397800a12449cffe50418",
                    "subCategoryId": "6793c149f406ee7da2520cda",
                    "name": "BMW X6",
                    "description": "BMW X6 New Generation",
                    "isDeleted": false,
                    "createdAt": 1737741996593,
                    "modifiedAt": 1737741996593,
                    "_id": "6793d6ac17808a96187c3d9e",
                    "__v": 0
                  }
                }
              }
            }
          }
        }
      }
    },
    "/all": {
      "get": {
        "tags": ["Products"],
        "summary": "Get all Products",
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "247"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"f7-08rb7L7Ohjd5OgG4P83mYrb7460\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 24 Jan 2025 18:08:00 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "products": [
                    {
                      "_id": "6793d6ac17808a96187c3d9e",
                      "categoryId": "679397800a12449cffe50418",
                      "subCategoryId": "6793c149f406ee7da2520cda",
                      "name": "BMW X6",
                      "description": "BMW X6 New Generation",
                      "createdAt": 1737741996593,
                      "modifiedAt": 1737741996593,
                      "__v": 0
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/{id}": {
      "get": {
        "tags": ["User"],
        "summary": "Get User By Id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "schema": {
              "type": "integer"
            },
            "required": true,
            "example": "3128955"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "237"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"ed-r1FAxrS/Jkleb5Q6Q5VrGGsMsl4\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sat, 18 Jan 2025 17:10:10 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "user": {
                    "_id": "678bc409e439a0a649f0e40b",
                    "memberId": 5215999,
                    "name": "Omar Ashraf",
                    "avatar": "Sat Jan 18 2025person_1.jpeg",
                    "email": "omar@syria.com",
                    "followers": 0,
                    "following": 0,
                    "createdAt": 1737212891421,
                    "modifiedAt": 1737212891421,
                    "__v": 0
                  }
                }
              }
            }
          }
        }
      },
      "patch": {
        "tags": ["User"],
        "summary": "Update User By Id",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "Mahmoud Abdallah"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "noauthAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "schema": {
              "type": "integer"
            },
            "required": true,
            "example": "5215999"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "385"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"181-giL5nqFgR/xcJtHhDzyZRKkajo0\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sat, 18 Jan 2025 17:17:16 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "User updated successfully",
                  "user": {
                    "_id": "678bc409e439a0a649f0e40b",
                    "googleId": null,
                    "memberId": 5215999,
                    "name": "Mahmoud Ahmed",
                    "avatar": "Sat Jan 18 2025person_1.jpeg",
                    "email": "omar@syria.com",
                    "password": "$2b$10$pF/pfuS7jZXD6XMB6zdsTeqhXeF6Viq4T6gp.vxEV6LacV1pULige",
                    "followers": 0,
                    "following": 0,
                    "isDeleted": false,
                    "createdAt": 1737212891421,
                    "modifiedAt": 1737212891421,
                    "__v": 0
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["User"],
        "summary": "Delete User By Id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "schema": {
              "type": "integer"
            },
            "required": true,
            "example": "4870562"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "39"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"27-27o4zzUjhHNmthTJyia4gBCjpos\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sat, 18 Jan 2025 23:03:36 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "User deleted successfully"
                }
              }
            }
          }
        }
      }
    },
    "/{id}/follow": {
      "post": {
        "tags": ["User"],
        "summary": "Follow User",
        "description": "**Here in this endpoint, Make sure that you pass a member Id of the user you want to follow.**",
        "requestBody": {
          "content": {}
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "schema": {
              "type": "integer"
            },
            "required": true,
            "example": "3079765"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "60"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"3c-5GTNpY6iKksbnJ8cmZKybK0nApw\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sat, 25 Jan 2025 15:44:45 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "You are now following أحمد حامد على"
                }
              }
            }
          }
        }
      }
    },
    "/profile/followers": {
      "get": {
        "tags": ["User"],
        "summary": "Get My Followers",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "275"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"113-Dy8r+JdYd1t15ltSyFM0Gnbb5Nc\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sat, 25 Jan 2025 11:31:35 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "followers": [
                    {
                      "_id": "6793e9f9383409f8cf68c33a",
                      "memberId": 3020393,
                      "name": "محمود محمد علي",
                      "avatar": null,
                      "email": "mahmoud@syria.com",
                      "followers": [],
                      "following": ["6793e96c383409f8cf68c336"],
                      "createdAt": 1737746756979,
                      "modifiedAt": 1737746756979,
                      "__v": 1
                    }
                  ],
                  "length": 1
                }
              }
            }
          }
        }
      }
    },
    "/profile/followings": {
      "get": {
        "tags": ["User"],
        "summary": "Get My Followings",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "258"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"102-6T0BOaSbhma3tcTqi8tWg2chsWs\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sat, 25 Jan 2025 11:41:07 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "following": [
                    {
                      "_id": "6793e96c383409f8cf68c336",
                      "memberId": 3128955,
                      "name": "Ahmed Hamed",
                      "avatar": null,
                      "email": "ahmed@syria.com",
                      "followers": ["6793e9f9383409f8cf68c33a"],
                      "following": [],
                      "createdAt": 1737746756979,
                      "modifiedAt": 1737746756979,
                      "__v": 1
                    }
                  ],
                  "length": 1
                }
              }
            }
          }
        }
      }
    },
    "/6795004170a40bca20db877f/rate": {
      "post": {
        "tags": ["User"],
        "summary": "Rate User",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "rate": 5,
                  "message": "راجل محترم والتعامل معاه قمة فى الشفافية"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "261"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"105-dwsa2R3Vu5TIqynNa/VAHB3ltdA\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sat, 25 Jan 2025 15:19:37 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Rating added successfully!",
                  "ratings": [
                    {
                      "ratedBy": "6795003070a40bca20db877b",
                      "rating": 5,
                      "message": "راجل محترم والتعامل معاه قمة فى الشفافية",
                      "_id": "6795010970a40bca20db8788",
                      "createdAt": "2025-01-25T15:19:37.380Z"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/profile/ratings": {
      "get": {
        "tags": ["User"],
        "summary": "Get Ratings List",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "327"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"147-fI0nUfKJukGZsvStbf7pzV2kBXE\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sat, 25 Jan 2025 15:25:04 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Rating statistics fetched successfully",
                  "ratings": [
                    {
                      "ratedBy": "6795003070a40bca20db877b",
                      "rating": 5,
                      "message": "راجل محترم والتعامل معاه قمة فى الشفافية",
                      "_id": "6795010970a40bca20db8788",
                      "createdAt": "2025-01-25T15:19:37.380Z"
                    }
                  ],
                  "ratingPercentages": {
                    "1": 0,
                    "2": 0,
                    "3": 0,
                    "4": 0,
                    "5": 100
                  }
                }
              }
            }
          }
        }
      }
    },
    "/679399e864e62593d54d4123": {
      "get": {
        "tags": ["Category"],
        "summary": "Get Category By Id",
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "257"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"101-5cIRb9dVUjh/zm6J4a4moiQdt3s\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 24 Jan 2025 13:53:30 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "user": {
                    "_id": "679399e864e62593d54d4123",
                    "name": "العقارات",
                    "description": "تشمل هذه الفئة عدد من العقارات المتاحة للبيع وتفاصيل كل وحدة",
                    "createdAt": 1737726390427,
                    "modifiedAt": 1737726390427,
                    "__v": 0
                  }
                }
              }
            }
          }
        }
      },
      "patch": {
        "tags": ["Category"],
        "summary": "Update By Id",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "الوحدات العقارية"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "336"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"150-KBa/2VHsDRJe0PnFv/LPC7H5Sks\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 24 Jan 2025 14:09:24 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Category updated successfully",
                  "category": {
                    "_id": "679399e864e62593d54d4123",
                    "name": "الوحدات العقارية",
                    "description": "تشمل هذه الفئة عدد من العقارات المتاحة للبيع وتفاصيل كل وحدة",
                    "isDeleted": false,
                    "createdAt": 1737726390427,
                    "modifiedAt": 1737727764842,
                    "__v": 0
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["Category"],
        "summary": "Delete Category By Id",
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "43"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"2b-oSB9C9UJoaUkZ5Mu5gkTHkZwuV4\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 24 Jan 2025 14:13:41 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Category deleted successfully"
                }
              }
            }
          }
        }
      }
    },
    "/6793c149f406ee7da2520cda": {
      "get": {
        "tags": ["SubCategory"],
        "summary": "Get SubCategory By Id",
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "228"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"e4-n0X6rnvNceGn9oZcWtezFd+1jW0\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 24 Jan 2025 16:40:01 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "subCategory": {
                    "_id": "6793c149f406ee7da2520cda",
                    "categoryId": "679397800a12449cffe50418",
                    "name": "BMW",
                    "icon": "Fri Jan 24 2025logo.png",
                    "description": "BMW Trade Mark",
                    "createdAt": 1737736497380,
                    "modifiedAt": 1737736497380,
                    "__v": 0
                  }
                }
              }
            }
          }
        }
      },
      "patch": {
        "tags": ["SubCategory"],
        "summary": "Update By Id",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "icon": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "310"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"136-sBk/TA/SABBMvmFgGPXO04kS/OA\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 24 Jan 2025 16:43:17 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "SubCategory updated successfully",
                  "subCategory": {
                    "_id": "6793c149f406ee7da2520cda",
                    "categoryId": "679397800a12449cffe50418",
                    "name": "BMW X6 Generation",
                    "icon": "Fri Jan 24 2025robotics.jpeg",
                    "description": "BMW Trade Mark",
                    "isDeleted": false,
                    "createdAt": 1737736497380,
                    "modifiedAt": 1737736997923,
                    "__v": 0
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["SubCategory"],
        "summary": "Delete Sub Category By Id",
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "43"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"2b-oSB9C9UJoaUkZ5Mu5gkTHkZwuV4\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 24 Jan 2025 14:13:41 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Category deleted successfully"
                }
              }
            }
          }
        }
      }
    },
    "/6793d6ac17808a96187c3d9e": {
      "get": {
        "tags": ["Products"],
        "summary": "Get Product By Id",
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "244"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"f4-wodvhL+6aH3YRWwbOR/1RFoHyAA\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 24 Jan 2025 18:08:59 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "product": {
                    "_id": "6793d6ac17808a96187c3d9e",
                    "categoryId": "679397800a12449cffe50418",
                    "subCategoryId": "6793c149f406ee7da2520cda",
                    "name": "BMW X6",
                    "description": "BMW X6 New Generation",
                    "createdAt": 1737741996593,
                    "modifiedAt": 1737741996593,
                    "__v": 0
                  }
                }
              }
            }
          }
        }
      },
      "patch": {
        "tags": ["Products"],
        "summary": "Update By Id",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "X6 new generation"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "314"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"13a-S+0YERY1VLIKnBIKR/3ve28nDlc\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 24 Jan 2025 18:10:48 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Product updated successfully",
                  "product": {
                    "_id": "6793d6ac17808a96187c3d9e",
                    "categoryId": "679397800a12449cffe50418",
                    "subCategoryId": "6793c149f406ee7da2520cda",
                    "name": "X6 new generation",
                    "description": "BMW X6 New Generation",
                    "isDeleted": false,
                    "createdAt": 1737741996593,
                    "modifiedAt": 1737742248319,
                    "__v": 0
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["Products"],
        "summary": "Delete Product By Id",
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "43"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"2b-oSB9C9UJoaUkZ5Mu5gkTHkZwuV4\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 24 Jan 2025 14:13:41 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Category deleted successfully"
                }
              }
            }
          }
        }
      }
    }
  }
}
